[project]
name = "torch2.2.0_cuda12.1_ubuntu22.04_base"
version = "1.0.142"
requires-python = ">=3.10"
dependencies = [ "gai-sdk>=0.256",]

[build-system]
requires = [ "setuptools>=61.0",]
build-backend = "setuptools.build_meta"
